_target_: dynamics_toolbox.models.pl_models.sequential_models.corr_pnn.CorrPNN
encode_dim: 32
rnn_num_layers: 1
rnn_hidden_size: 128
decoder_num_hidden_layers: 4
decoder_hidden_size: 512
logvar_lower_bound: -10
logvar_upper_bound: 0.5
corr_lower_bound: -0.05
corr_upper_bound: 0.05
dim_name_map:
  - "Rewards"
  - "X Position"
  - "Y Position"
  - "Angular Velocity"
