_target_: dynamics_toolbox.models.pl_models.sequential_models.corr_uq.CorrUQ
base_model_is_sequential: False
base_model:
  _target_: dynamics_toolbox.models.pl_models.pnn.PNN
  encoder_output_dim: 200
  encoder_cfg:
     _target_: dynamics_toolbox.models.pl_models.mlp.MLP
     num_layers: 3
     layer_size: 200
     hidden_activation: "swish"
  mean_net_cfg:
     _target_: dynamics_toolbox.models.pl_models.mlp.MLP
     num_layers: 0
     layer_size: 200
     hidden_activation: "swish"
  logvar_net_cfg:
     _target_: dynamics_toolbox.models.pl_models.mlp.MLP
     num_layers: 0
     layer_size: 200
     hidden_activation: "swish"
  logvar_lower_bound: -20
  logvar_upper_bound: -5
uq_encode_dim: 32
uq_rnn_num_layers: 1
uq_rnn_hidden_size: 128
uq_decoder_num_hidden_layers: 4
uq_decoder_hidden_size: 512
dim_name_map:
  - "Rewards"
  - "X Position"
  - "Y Position"
  - "Angular Velocity"
