_target_: dynamics_toolbox.models.pl_models.neural_process.NeuralProcess
condition_out_dim: 256
latent_dim: 2
learning_rate: 0.0001
conditioner_cfg:
    #  _target_: dynamics_toolbox.util.pytorch.modules.dataset_encoder.MLPDatasetEncoder
    #  mlp_kwargs:
    #     _target_: dynamics_toolbox.models.pl_models.mlp.MLP
    #     num_layers: 3
    #     layer_size: 200
    #     hidden_activation: "relu"
   _target_: dynamics_toolbox.utils.pytorch.modules.dataset_encoder.SelfAttentionDatasetEncoder
   query_net_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 3
       layer_size: 200
       hidden_activation: "relu"
   key_net_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 3
       layer_size: 200
       hidden_activation: "relu"
   value_net_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 3
       layer_size: 200
       hidden_activation: "relu"
latent_encoder_cfg:
    _target_: dynamics_toolbox.models.pl_models.pnn.PNN
    encoder_output_dim: 200
    encoder_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 3
       layer_size: 200
       hidden_activation: "relu"
    mean_net_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 0
       layer_size: 200
       hidden_activation: "relu"
    logvar_net_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 0
       layer_size: 200
       hidden_activation: "relu"
    logvar_lower_bound: -10
    logvar_upper_bound: 0.5
decoder_cfg:
    _target_: dynamics_toolbox.models.pl_models.mlp.MLP
    num_layers: 3
    layer_size: 200
    hidden_activation: "tanh"
