model_name: "NeuralProcess"
model_type: "NeuralProcess"
condition_out_dim: 256
latent_dim: 2
learning_rate: 0.0001
conditioner_kwargs:
    model_name: "Conditioner"
    model_type: "MLPDatasetEncoder"
    mlp_kwargs:
       num_layers: 3
       layer_size: 200
       hidden_activation: "relu"
    #     model_type: "SelfAttentionDatasetEncoder"
    #     query_net_kwargs:
    #         num_layers: 3
    #         layer_size: 256
    #         hidden_activation: "relu"
    #     value_net_kwargs:
    #         num_layers: 3
    #         layer_size: 256
    #         hidden_activation: "relu"
    #     key_net_kwargs:
    #         num_layers: 3
    #         layer_size: 256
    #         hidden_activation: "relu"
latent_encoder_kwargs:
    model_name: "Encoder"
    model_type: "PNN"
    encoder_num_layers: 3
    encoder_layer_size: 200
    encoder_output_dim: 200
    mean_architecture: "200_200"
    logvar_architecture: "200_200"
    logvar_lower_bound: -10
    logvar_upper_bound: 0.5
    hidden_activation: "swish"
decoder_kwargs:
    model_name: "Decoder"
    model_type: "MLP"
    num_layers: 3
    layer_size: 200
    hidden_activation: "tanh"
