model_name: "PNN"
model_type: "PNN"
encoder_architecture: "200_200_200"
encoder_output_dim: 200
mean_architecture: ""
logvar_architecture: ""
logvar_lower_bound: -10
logvar_upper_bound: 0.5
logvar_bound_loss_coef: 0.01
learning_rate: 0.0001
hidden_activation: "swish"
