_target_: dynamics_toolbox.models.pl_models.pnn.PNN
encoder_output_dim: 200
encoder_cfg:
   _target_: dynamics_toolbox.models.pl_models.mlp.MLP
   num_layers: 3
   layer_size: 200
   hidden_activation: "swish"
mean_net_cfg:
   _target_: dynamics_toolbox.models.pl_models.mlp.MLP
   num_layers: 0
   layer_size: 200
   hidden_activation: "swish"
logvar_net_cfg:
   _target_: dynamics_toolbox.models.pl_models.mlp.MLP
   num_layers: 0
   layer_size: 200
   hidden_activation: "swish"
logvar_lower_bound: -10
logvar_upper_bound: 0.5
# dim_name_map:
#   - "Rewards"
#   - "X Position"
#   - "Y Position"
#   - "Angular Velocity"
