model_name: "QuantileModel"
model_type: "QuantileModel"
encoder_architecture: "200_200_200"
loss_function: "pinball"
num_quantile_draws: 30
learning_rate: 0.0001
hidden_activation: "swish"
input_dim: 1
output_dim: 1
