_target_: dynamics_toolbox.models.pl_models.sequential_models.sequential_dynamics_models.dynamics_rpnn.DynamicsRPNN
encode_dim: 512
num_layers: 2
hidden_size: 512
encoder_cfg:
   _target_: dynamics_toolbox.models.pl_models.mlp.MLP
   num_layers: 2
   layer_size: 512
   hidden_activation: "relu"
pnn_decoder_cfg:
    _target_: dynamics_toolbox.models.pl_models.pnn.PNN
    encoder_output_dim: 512
    encoder_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 2
       layer_size: 512
       hidden_activation: "swish"
    mean_net_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 0
       layer_size: 200
       hidden_activation: "swish"
    logvar_net_cfg:
       _target_: dynamics_toolbox.models.pl_models.mlp.MLP
       num_layers: 0
       layer_size: 200
       hidden_activation: "swish"
    logvar_lower_bound: -10
    logvar_upper_bound: 0.5
