_target_: dynamics_toolbox.models.pl_models.sequential_models.rpnn.RPNN
encode_dim: 128
rnn_num_layers: 1
rnn_hidden_size: 32
logvar_lower_bound: -10
logvar_upper_bound: 0.5
encoder_cfg:
   _target_: dynamics_toolbox.models.pl_models.mlp.MLP
   num_layers: 1
   layer_size: 128
   hidden_activation: "relu"
pnn_decoder_cfg:
  _target_: dynamics_toolbox.models.pl_models.pnn.PNN
  encoder_output_dim: 200
  encoder_cfg:
     _target_: dynamics_toolbox.models.pl_models.mlp.MLP
     num_layers: 1
     layer_size: 128
     hidden_activation: "relu"
  mean_net_cfg:
     _target_: dynamics_toolbox.models.pl_models.mlp.MLP
     num_layers: 0
     layer_size: 128
     hidden_activation: "relu"
  logvar_net_cfg:
     _target_: dynamics_toolbox.models.pl_models.mlp.MLP
     num_layers: 0
     layer_size: 128
     hidden_activation: "relu"
dim_name_map:
  - "Rewards"
  - "X Position"
  - "Y Position"
  - "Angular Velocity"
