_target_: dynamics_toolbox.models.pl_models.sequential_models.sequential_dynamics_models.dynamics_transformer.DynamicsTransformer
num_hidden: 4
ff_dim: 128
embed_dim: 64
num_heads: 3
dropout_prob: 0.1
warm_up_period: 5


