# experiment_name: "disrupt_model"
# run_name: "dataset_2022-10-12"
# data_source: "/zfsauton2/home/youngsec/research/fusion/disruption/model_data_file_fixed.h5"
experiment_name: "benchmark_data_pnn"
run_name: "PASS"
data_source: "PASS"
seed: 1
logger: tensorboard
normalization: "standardize"
defaults:
    - trainer: pl_trainer
    - data_module: regression_data_module
    - early_stopping: default
    - model: pnn

trainer:
    max_epochs: 10000
#     max_epochs: 10
    devices: 2
    accelerator: 'gpu'
data_module:
    batch_size: 128
    val_proportion: 0.0
    test_proportion: 0.0
    num_workers: 16
save_dir: "PASS"
gpus: 1

# the below actually doesn't do anything
model:
    num_layers: 10
    layer_size: 200



      # hydra:
      #     job:
      #         name: ${name}
      #     run:
      #         dir: results/${name}/${now:%Y-%m-%d-%H-%M}
