experiment_name: "dynamics-toolbox"
run_name: "test"
data_source: ???
seed: 1
logger: tensorboard
# normalization: "standardize"
defaults:
    - trainer: pl_trainer
    - data_module: forward_dynamics_data_module
      # - early_stopping: default
