# experiment_name: "disrupt_model"
# run_name: "dataset_2022-10-12"
# data_source: "/zfsauton2/home/youngsec/research/fusion/disruption/model_data_file_fixed.h5"
experiment_name: "rohit_exercise_dt_data_for_disruption"
run_name: "base_case"
# data_source: "/home/scratch/youngsec/rs/fusion/disruption/datasets/scan_use_as_input_with_ip/scan_use_as_input_(act-nact-prof).h5"
data_source: "/zfsauton/project/public/ysc/joe_dataset/dt_data_for_disruption.h5"
seed: 1
logger: tensorboard
normalization: "standardize"
defaults:
    - trainer: pl_trainer
    - data_module: regression_data_module
    - early_stopping: default
    - model: mlp

trainer:
    max_epochs: 3000 #3000
    devices: 1
    accelerator: 'gpu'
    auto_select_gpus: 2
data_module:
    batch_size: 512
    val_proportion: 0.0
    test_proportion: 0.0
    num_workers: 16
save_dir: "/home/scratch/rsonker/disruption/ex1"
gpus: [1,2]

# modifications 1: make the network bigger
model:
    num_layers: 5 #5
    layer_size: 300 #300

      # hydra:
      #     job:
      #         name: ${name}
      #     run:
      #         dir: results/${name}/${now:%Y-%m-%d-%H-%M}