experiment_name: "dynamics-toolbox"
run_name: "test"
data_source: ???
seed: 1
logger: tensorboard
# normalization: "standardize"
defaults:
        - trainer: pl_trainer
        - data_module: sequential_rl_data_module
        - early_stopping: default
        - model: transformer
    #  - model: mlp
    # - trainer: pl_trainer
    #  - data_module: forward_dynamics_data_module
    #  - early_stopping: default
            # hydra:
            #     job:
            #         name: ${name}
            #     run:
            #         dir: results/${name}/${now:%Y-%m-%d-%H-%M}
