name: ???
env_name: ???
seed: 0
cuda_device: null
env:
  _target_: gym.make
  id: ${env_name}
train_loop:
  _target_: dynamics_toolbox.rl.train_loops.offline_mbrl_training
  epochs: 1000
  num_expl_paths_per_epoch: 50e3
  num_eval_eps: 10
  model_horizon: 5
  eval_horizon: 1000
  num_gradient_steps_per_epoch: 1000
  batch_size: 256
  model_env:
    _target_: dynamics_toolbox.env_wrappers.model_env.ModelEnv
    unscale_penalizer: True
    dynamics_model:
      _target_: dynamics_toolbox.utils.storage.model_storage.load_ensemble_from_parent_dir
      parent_dir: 'trained_models/d4rl_v2/${env_name}/${seed}'
      sample_mode: 'sample_member_every_step'
      load_n_best_models: 5
    penalizer:
      _target_: dynamics_toolbox.env_wrappers.penalizers.get_penalizer
      pen_name: 'std'
    penalty_coefficient: 1.0
    terminal_function:
      _target_: dynamics_toolbox.env_wrappers.wrapper_utils.get_terminal_from_env_name
      env_name: ${env_name}
    bounder:
        _target_: dynamics_toolbox.env_wrappers.bounders.Bounder.bound_from_dataset
        spread_amt: 10
        data:
          _target_: dynamics_toolbox.utils.storage.qdata.load_from_hdf5
          hdf5_path: 'data/d4rl/${env_name}.hdf5'
          relative_path: True
  model_buffer:
    _target_: dynamics_toolbox.rl.buffers.simple_buffer.SimpleReplayBuffer
    max_buffer_size: 1e6
  env_buffer:
    _target_: dynamics_toolbox.rl.buffers.simple_buffer.SimpleOfflineReplayBuffer
    data:
      _target_: dynamics_toolbox.utils.storage.qdata.load_from_hdf5
      hdf5_path: 'data/d4rl/${env_name}.hdf5'
      relative_path: True
  logger:
    _target_: dynamics_toolbox.rl.rl_logger.RLLogger
algorithm:
  _target_: dynamics_toolbox.rl.algorithms.sac.SAC
  discount: 0.99
  learning_rate: 3e-4
  target_entropy: -3
  soft_target_update_weight: 5e-3
  soft_target_update_frequency: 1
  entropy_tune: True
  num_qnets: 2
  policy:
    _target_: dynamics_toolbox.rl.modules.policies.TanhGaussianPolicy
    hidden_sizes:
      - 256
      - 256
  qnet:
    _target_: dynamics_toolbox.rl.modules.valnets.QNet
    hidden_sizes:
      - 256
      - 256
hydra:
  run:
    dir: logs/mopo_baselines/${name}/${seed}
