model_name: "MLP"
model_type: "MLP"
num_ensemble_members: 1
sequential_train: False # TODO: If True each member is trained sequentially.
hidden_sizes: "200_200_200"
learning_rate: 0.0001
hidden_activation: "relu"
