_target_: dynamics_toolbox.data.cb_data_modules.classification_data_module.CBClassificationDataModule
batch_size: 256
val_proportion: 0.0
test_proportion: 0.0
pin_memory: True
num_workers: 1
# num_classes: 3
num_classes: 2
