_target_: dynamics_toolbox.data.pl_data_modules.forward_dynamics_data_module.ForwardDynamicsDataModule
batch_size: 256
learn_rewards: True
val_proportion: 0.05
test_proportion: 0.0
pin_memory: True
num_workers: 1
