_target_: dynamics_toolbox.data.pl_data_modules.timeseries_data_module.TimeseriesDataModule
data_source_is_single_timeseries: True
batch_size: 64
val_proportion: 0.1
test_proportion: 0.1
pin_memory: False
num_workers: 1
snippet_size: 10
